version: '4.0'

actions:
  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/ehrql_dataset_definition.py --output output/dataset.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset.csv.gz
